### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by RSully** [walterra/J4p5Bundle#1]
Getting this error:

```
PHP Fatal error:  Class 'Walterra\J4p5Bundle\j4p5\jsrt\js_object' not found in ~/dev/myproject/vendor/walterra/j4p5-bundle/Walterra/J4p5Bundle/j4p5/jsrt.php on line 86
```

This is my first time using composer so it could be something I am overlooking. 

In my code I'm doing something like this (not exactly):

``` php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Walterra\J4p5Bundle\j4p5;

class SomeClass {
    public function someFunction()
    {
        j4p5\js::run('console.log("test");');
    }
}

$obj = new SomeClass();
$obj->someFunction();
```

**Comment by RSully** [comment]
With a fresh install and simple file I'm getting a different error now:

```
PHP Fatal error:  Class 'Walterra\J4p5Bundle\j4p5\parse\preg_scanner' not found in ~/dev/myproject/vendor/walterra/j4p5-bundle/Walterra/J4p5Bundle/j4p5/jsc.php on line 40
```

``` php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Walterra\J4p5Bundle\j4p5;

j4p5\js::run('console.log("test")');
```

**Comment by walterra** [comment]
Please try running from terminal:

`php composer.phar dump-autoload --optimize`

This should create a static autoload file. I'm not sure why it's not working with dynamic autoloading yet.

Please change "console.log" to "print" and try again, console.log is not supported.
